language: node_js
node_js:
    - "0.10"
before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - npm install
    - bower install
notifications:
    email:
        on_success: change
        on_failure: change
env:
  global:
    - secure: V5csRamm/tlqYKATPX5E9gpAJwsbxczBSlbTPaX9M2dyvGbzWjuJO7x62NEOly2FndKRMnSmp3R7ZlqORgBn1D5/K8lpwZcm4L1olfPpGJL5trIw0oWJo2Q6k/NpKUwV4aFN96NS75jxHztbUsnzrDLRRsNPxAcwKo//Q/PCB4I=
    - secure: Mt4gFX8AeFx33L+OI7uJlXr8kvvHU6nesmRful2e9HpQMbKO3xRyesxS93xXsCTloxEoCWl0+2NPRuU++UCcts/JrD0SMEeZRnk2K5wOyZJRIVCq3U/40dN7odbQI7Y5MQ6ykPlFve5NUvBrggpn1D/jwap5DYgKN93qR6PWKDk=
sudo: false
cache:
    directories:
        - node_modules
